// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Lx7L-0tvAIHb4xsv1GeJy_p6B-2mXTE',
    appId: '1:525406201811:android:2da8ad60f9e24f5a3ef126',
    messagingSenderId: '525406201811',
    projectId: 'flutter-webrtc--demo',
    storageBucket: 'flutter-webrtc--demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEVrNjTHsy9s3TD4p467bNb3Tbm7WSHM',
    appId: '1:525406201811:ios:1148ca527f5dbb2d3ef126',
    messagingSenderId: '525406201811',
    projectId: 'flutter-webrtc--demo',
    storageBucket: 'flutter-webrtc--demo.appspot.com',
    iosBundleId: 'com.example.flutterWebrtc',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MK4DNv_AiDJ1SDiZrjd7nXndsnerqFM',
    appId: '1:525406201811:web:73bc7a40d0fb4c843ef126',
    messagingSenderId: '525406201811',
    projectId: 'flutter-webrtc--demo',
    authDomain: 'flutter-webrtc--demo.firebaseapp.com',
    storageBucket: 'flutter-webrtc--demo.appspot.com',
  );

}